version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_DATABASE: 'vlpidb'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
        # Exposed Port : Container Port
        - '3308:3306'
    volumes:
        - my-db:/var/lib/mysql

volumes:
  my-db:

